### ISSUE TITLE
Possibly Related to the Flight Table v1.1.1

### ISSUE THREAD

**Issue by kreezxil** [Gakai/GakaisFlightTable#4]
We have RF in the SkyCraft 1.8 Extreme Mega Pack, one provided by Vanhal's Progressive Automation and another Provided by Neotech. They're both based on different versions of the RF API as there is no official version for 1.8 as you are aware. 

I suspect this error is coming from the flight table because we can actually force this particular error by hooking an RF pipe up to it.

As to whether or not this particular error is a result of that I can not say for sure as I don't know where in my world someone would have hooked the flight table up to an RF pipe. Need an option to disable that if it is not supported.

```
[12:46:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:710) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NoSuchMethodError: cofh.api.energy.IEnergyReceiver.receiveEnergy(Lnet/minecraft/util/EnumFacing;IZ)I
        at com.dyonovan.neotech.common.tileentity.generator.TileFluidGenerator.transferEnergy(TileFluidGenerator.java:89) ~[TileFluidGenerator.class:?]
        at com.dyonovan.neotech.common.tileentity.generator.TileFluidGenerator.func_73660_a(TileFluidGenerator.java:62) ~[TileFluidGenerator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1735) ~[aqu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
        ... 4 more
```

Issue: flight table 1.1.1 crashing server when flight table gets ticked after an rf pipe which is not supported gets interfaced to it

crash report:
https://gist.github.com/f1e694b9428b6dd80ba6

fml server latest:
https://gist.github.com/6c471156f3ea306cbf5c

**Comment by Gakai** [comment]
The 1.8 version does not contain any redstone flux API at all, so it should behave like any normal block.

**Comment by kreezxil** [comment]
Ok that is weird then, meaning it doesn't even connect to RF at all.

**Comment by beyondthewall** [comment]
hello,

just fyi: this error is triggered when rf energy is transported from the generator into the energy pipe (neotech). the same happens if you transport items from any inventory into a itempipe (also neotech). i am positive it has nothing todo with the flight table and must be a neotech bug. (bug report: https://github.com/TeamBR-Modding/NeoTech/issues/32)
